### ISSUE TITLE
No one hears you. Your account has been flagged as disruptive

### ISSUE THREAD

**Issue by mystvearn** [ValveSoftware/Dota2-Gameplay#10068]
### Description

I open Dota today. After match start, the following message appears. 

No one hears you. Your account has been flagged as disruptive ...

It seems like not only me who got this issue but other players as well. We could only chat after the game

**Comment by sdasrc** [comment]
Piggybacking on this as its the same for me. I had a 10k behaviour score and now it says it tanked to 3k in a single game.

**Comment by f9dfk** [comment]
> Piggybacking on this as its the same for me. I had a 10k behaviour score and now it says it tanked to 3k in a single game.

Same.
![3K SCORE](https://github.com/ValveSoftware/Dota2-Gameplay/assets/131423762/ec66fb5b-f318-4f88-ba0d-59a5ec413db7)

**Comment by Daniel-Jacobson-1819** [comment]
me as well guys 10k account long time today randomly cant chat

**Comment by cristisp** [comment]
Same for me

**Comment by drewdicaro** [comment]
![Untitled](https://github.com/ValveSoftware/Dota2-Gameplay/assets/139410180/938b7470-af80-41d0-8a08-ab579212efe6)
Same issue

**Comment by sdasrc** [comment]
It's working now. They prolly fixed it.

**Comment by mystvearn** [comment]
> It's working now. They prolly fixed it.
> 
> Edit: Worst part - I think i played muuuch better with chat turned off xd (I know its not true but oh well, cheers!)

Yes it's fixed now. Indeed I think muting both team is good for Dota lol. Suddenly everyone focused on playing the game.

**Comment by drewdicaro** [comment]
> It's working now. They prolly fixed it.
> 
> Edit: Worst part - I think i played muuuch better with chat turned off xd (I know its not true but oh well, cheers!)

Mine is still not working, did you have to do anything besides restart steam?

**Comment by mystvearn** [comment]
> > It's working now. They prolly fixed it.
> > Edit: Worst part - I think i played muuuch better with chat turned off xd (I know its not true but oh well, cheers!)
> 
> Mine is still not working, did you have to do anything besides restart steam?

@drewdicaro I have to upgrade Dota too. It might take sometimes for new update to arrive to everyone.

**Comment by drewdicaro** [comment]
> > > It's working now. They prolly fixed it.
> > > Edit: Worst part - I think i played muuuch better with chat turned off xd (I know its not true but oh well, cheers!)
> > 
> > 
> > Mine is still not working, did you have to do anything besides restart steam?
> 
> @drewdicaro I have to upgrade Dota too. It might take sometimes for new update to arrive to everyone.

It finally came! wahoo

**Comment by Nathanael-Valve** [comment]
Fixed
