### ISSUE TITLE
VSync doesn't work after the summer client update.

### ISSUE THREAD

**Issue by revdepign** [ValveSoftware/Dota2-Gameplay#11107]
### Description

Title. I have a 60 Hz monitor, so before the patch, the game client worked at 60 FPS. After the patch, my game client is working with much faster FPS. Can you please honor the VSync setting?

### Example Match ID (and possibly Timestamp)

NA

### Screenshots

![20230831184926_1](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143705201/76c1c2c4-6253-4c56-8641-00bf58c608ba)

**Comment by XkTheMaster** [comment]
Looks like Vsync is broken for me too , Windowed + Borderless Windowed.

**Comment by MarcosFloresIII** [comment]
Same with me Vsync is broken. 60hz refresh rate but the game is ignoring vsync ON.
![Dota 2 Screenshot 2023 08 31 - 20 35 34 26](https://github.com/ValveSoftware/Dota2-Gameplay/assets/131643570/1e6ddf62-c69e-4d59-ad15-310c72c89c58)

**Comment by revdepign** [comment]
7.34c is out, but still not fixed.

**Comment by MarcosFloresIII** [comment]
> 7.34c is out, but still not fixed.

I tried a fix and it seems to be working for now. Try going into Nvidia Control Panel then Manage 3D settings. Under Global Settings, turn Vertical Sync to On then click Apply. The default setting to this is 'Use the 3D Application setting' so you wanna change it to On. This forces all 3D programs(like Dota 2) to use VSync regardless of what's set in the application. That about fixed it for me. LMK if it works for you
![Screenshot 2023-09-09 174737](https://github.com/ValveSoftware/Dota2-Gameplay/assets/131643570/dc9c9de0-7bf4-404d-82ba-4edbb8283695)

**Comment by revdepign** [comment]
I noticed VSync is ignored when "Display Mode" is "Windowed" and effective when "Borderless Window". Can you fix "Windowed" case, please?

**Comment by fireattack** [comment]
Mine does not work even in borderless window.

**Comment by K0uGou** [comment]
Still an issue - doesn't seem to be addressed at all.

**Comment by IgorHoruzha** [comment]
#15078 I also has the same issue.

**Comment by revdepign** [comment]
It seems to have been fixed.

**Comment by IgorHoruzha** [comment]
@revdepign Interesting. I still have the same issue. Could You provide how You have fixed it, please?

**Comment by revdepign** [comment]
@IgorHoruzha I do nothing in particular. I just use the same settings as before.

![d260](https://github.com/ValveSoftware/Dota2-Gameplay/assets/143705201/e86b08f2-ed9e-4cdc-81d1-b2535927bb22)

**Comment by IgorHoruzha** [comment]
@XkTheMaster 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/a3de4032-7afb-468a-bbcf-02be5cc19fb8)
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/29505510/6ce09192-95ab-4757-ac90-9c3a14641d7a)

Is a mistake on my side?
