### ISSUE TITLE
Astral Imprisonment stacks calculating remaining mana wrongly

### ISSUE THREAD

**Issue by shprdGit** [ValveSoftware/Dota2-Gameplay#1113]
### Ability name

Astral Imprisonment

### Description

Hello Jeff!

Today in a game I noticed that I (dire Leshrac) would be losing mana in huge chunks when (radiant) Outworld Devourer's Astral Imprisonment spell stacks would be running out.
Game ID: 6612716538
A good example is if you watch minute 8:30 to 8:34.
I'm at mid tower and got quite a few stacks on me starting to run out. At 8:34 my mana is 420/445 and as the max mana gets restored I suddenly drop to 181/571. Some math is not adding up here. :) 

### Example Match ID (and possibly Timestamp)

6612716538

**Comment by TheUnholyWrath** [comment]
![Capture](https://user-images.githubusercontent.com/46859977/173209255-acdcca5d-e1f7-4060-9c34-5032bec83b39.PNG)
This is a hero with 0 mana regen. I cast Astral Imprisonment on him 9 times. After the 1st stack of Astral wears off correctly he starts gaining Current Mana. The big chunks of mana you were losing was multiple stacks of Astral mistakenly giving you Current Mana and taking most of it away.

**Comment by TheUnholyWrath** [comment]
https://user-images.githubusercontent.com/46859977/173211455-5c1ecb9d-f52e-4194-ab40-eda9a51692eb.mp4

**Comment by sma11ram** [comment]
I think this could also be connected to [this issue](https://www.reddit.com/r/DotA2/comments/rpsozm/astral_imprisonment_does_not_make_any_sense/) that was posted on Reddit 5 months ago. 

Also, Singsing came across a similar issue [here](https://www.twitch.tv/videos/1504290613?t=3h59m16s). 

There are 3 Astral stacks on the Pudge in the video, and the expiration of each one of them behaves differently:

```
Before the 1st expiration: 196/196
After the 1st expiration: 196/286
```

The current mana didn't change while the max mana pool increased.

```
Before the 2nd expiration: 215/286
After the 2nd expiration: 286/356
```

The current mana increased to the previous max mana pool while the max mana pool increased.

```
Before the 3rd (final) expiration: 303/356
After the 3rd (final) expiration: 267/411
```

The max mana pool increased, but the current mana is even lower than before because the mana percentage stayed the same as before expiration. 

I don't think this is intended behavior, since every stack behaves differently. Also, even if OD uses just one Astral, the affected hero loses mana after the debuff expires  – just like what happened after the 3rd stack expired in the example above.

**Comment by huy236** [comment]
id: 6688854795

https://user-images.githubusercontent.com/64003011/182408151-7b4512d2-4737-44cc-a070-9f117a82b1d1.mp4

**Comment by Nathanael-Valve** [comment]
Fixed in next update.

**Comment by Wulfdragon** [comment]
not fixed.

this is still an issue as of now, after the big patch today....   it can even be seen in demo mode, when OD has multiple stacks of increased mana pool and a stack falls off, his CURRENT mana still gets affected.
