### ISSUE TITLE
Compendium update broke sound output to headphones on linux

### ISSUE THREAD

**Issue by neimovirne** [ValveSoftware/Dota2-Gameplay#12247]
### Description

After compendium update I'm not able to use any of my headphones. And in Dota2 settings there are lots of new but useless audio devices (see screenshot)

Sound output is now always through laptop speakers, even though headphones set as primary device in system settings
Ubuntu 23.04
GeForce gtx1060
6.2.0-33-generic kernel

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/2023595/3e0f537d-4fc4-4185-9bc1-cfe30e949043)

**Comment by pleish** [comment]
I am able to change the device and see it in the Dota console but no audio is logged or played. On Arch Linux latest.

**Comment by neimovirne** [comment]
And it seems like Dota forced to use pulseaudio instead of pipewire, it shows in overlay if I try to check mic settings
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/2023595/4c6f5af7-e4e1-4821-89ab-6c8397f7c90a)

**Comment by neimovirne** [comment]
fixes with adding launch key -sdlaudiodriver pipewire

**Comment by noxor0** [comment]
This doesn't work for pulse audio users, obviously ^

**Comment by paboum** [comment]
Another update, another bugs. Why don't they just leave the product alone? These should be detected in beta phase, aren't they earning money on the product so they could hire testers?

**Comment by MacOxJunDude** [comment]
The problem is easily solved by installing pipewire using the commands:
1. pactl info - (Server name: PulseAudio)
2. sudo apt install pipewire-audio-client-libraries libspa-0.2-bluetooth libspa-0.2-jack wireplumber
3. sudo apt remove pulseaudio-module-bluetooth
4. systemctl --user --now enable wireplumber.service
5. reboot
6. After reboot => pactl info - (Server name: PulseAudio (on PipeWire 0.3.48))
After these steps everything worked for me

**Comment by Forage** [comment]
Duplicate of #12230

**Comment by icculus** [comment]
Duplicate of https://github.com/ValveSoftware/Dota-2/issues/2491

**Comment by werefkin** [comment]
A solution for ubuntu users (e.g. 22.04) where pipewire is not (fully) installed.
1. Install pipewire sudo apt install p`ipewire-media-session- wireplumber`
2. reboot `sudo reboot`
3. Force Dota with a launching option: `-sdlaudiodriver pipewire`

optional: check `pactl info`, in my case Server Name: PulseAudio (on PipeWire 0.3.48)

**Comment by icculus** [comment]
See if this is fixed in the update from a few minutes ago.

**Comment by noxor0** [comment]
As an arch pulseaudio user, with no additional launch params, this is now fixed!

**Comment by DSDV** [comment]
can confirm works again on fedora / nobara 38 - still crashes tho ^

**Comment by neimovirne** [comment]
fixed now by valve
