### ISSUE TITLE
[Controller] Can anyone confirm me that the game controller works for them?

### ISSUE THREAD

**Issue by ice-blaze** [ValveSoftware/Dota2-Gameplay#12623]
### Description

I'm playing on windows 10 with an xbox one controller. I activated `dota_disable_controller_support 0`. While in game the camera moves directly to the top of the map. I can controll the hero because I see him moving on the minimap when using the gamepad. 

I'm just here to know if people have similar issues or if it's only on my side. 

Thank you for your help.

**Comment by ayellaz** [comment]
Yeah, I’ve been trying to figure it out for a week, and I’ve encountered the same issue.

**Comment by ice-blaze** [comment]
I'm glad to know someone else tried to play with the controller 🙏 I have the feeling no one play this game with a gamepad.

**Comment by Eduardo-Thiesen** [comment]
Tried yesterday on Steam Deck. Wasn't working for me either.

**Comment by ayellaz** [comment]
im still waiting for the fix , for my Rog Ally . 🙂

**Comment by BIEGYOSHI** [comment]
Yesterday night I tried. I typed the command in the console when I got into a game and I was able to use my controller (on Steam deck).

**Comment by Eduardo-Thiesen** [comment]
Tried today on Steam Deck and it worked. Added '+dota_disable_controller_support 0' to launch options of the game.

**Comment by ayellaz** [comment]
still not working on my ROG Ally 🥲

**Comment by ice-blaze** [comment]
Good to know that with the steam deck it works, but on my side (windows 10 + xbox one controller) it does't work :/

**Comment by weejiaquan** [comment]
Had this issue too

**Comment by ayellaz** [comment]
@ice-blaze same as me dude. still waiting

**Comment by Clocktown** [comment]
Can confirm your issue as well. I use a GuliKit Nintendo Switch Controller. Same behaviour, camera is only mapped to right stick on one axis, the other axis slides up by default and you can make it slide down with the left trigger. No idea how in the world one could mess it up this badly - even when I alt tab out of the game, this behaviour continues and overrides my regular mouse. Have to kill the game with task manager, ALT F4 doesn't do anything.

**Comment by javapit** [comment]
The same problem, the camera is controlled vertically with the left trigger, and controlled horizontally with the stick.

**Comment by nangkates** [comment]
does this issue still persist ? or does anyone find temporary fix for this ?

**Comment by ice-blaze** [comment]
@nangkates still present. I must say I'm quite happy with my situation now, I have so much free time x)

**Comment by roobeekspamma** [comment]
wanted to try playing with a controller (WIN10+DS4), @jeffhill pls help

**Comment by Eduardo-Thiesen** [comment]
Got a Dualsense, so I was able to verify the same behaviour reported here. I went into the game settings -> Properties... -> Controller -> Override for Dota 2 -> Changed from 'Disable Steam Input' to 'Enable Steam Input', and it worked. Can you guys test this on your end?

**Comment by ice-blaze** [comment]
Doesn't work for me. I'm not 100% sure if I changed it in the right place but here there is a screenshot of what I did 
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/3356843/f2a7911d-9ea5-49bf-bcb9-cdd7389e91e8)

**Comment by roobeekspamma** [comment]
i mean the controller works, but it just moves to the top of the map

**Comment by Eduardo-Thiesen** [comment]
@roobeekspamma I know. I was getting the same behaviour before changing that setting.

**Comment by roobeekspamma** [comment]
still doesn't work @Eduardo-Thiesen, did you have "dota_disable_controller_support 0" in your launch or console?

![Dota 2 Screenshot 2023 11 22 - 09 36 29 51](https://github.com/ValveSoftware/Dota2-Gameplay/assets/151618497/c63a39f0-7664-4be5-a358-12afd281e8c5)
![Capture](https://github.com/ValveSoftware/Dota2-Gameplay/assets/151618497/ede2107a-39cf-4fd1-a72d-cb69ced6f23b)

**Comment by Eduardo-Thiesen** [comment]
> still doesn't work @Eduardo-Thiesen, did you have "dota_disable_controller_support 0" in your launch or console?

Yes, I have that in launch options.

**Comment by roobeekspamma** [comment]
then it just doesn't work on my end

**Comment by bernikovich** [comment]
I reproduced this issue today on Windows 11 with an Xbox Series X controller using all the default settings.

**Comment by roobeekspamma** [comment]
then it's a windows issue. sux. valve pls fix

**Comment by ayellaz** [comment]
any solution about this issued . 😔

**Comment by Jackedses** [comment]
Valve, please fix gamepad control. 
We have been sitting without the opportunity to play the game for several months now.

**Comment by ice-blaze** [comment]
Just pinging since the problem now persist for 3 month. Maybe one day we will be rescued...
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/3356843/4a36286a-ffb1-4bb9-80c1-f701b49ab996)

**Comment by ayellaz** [comment]
🥹

**Comment by cmosboss** [comment]
Justice for Controller!

**Comment by SamRedFox** [comment]
Not fixed yet. Press F

**Comment by alfiancc** [comment]
i dont know if this helps.
but if you hold R3 , the camera will focus on hero and the game is playable(ish) xD
![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/160203540/0bc06040-0e4b-4b70-9c04-be9afeff1f4b)

**Comment by melancholie** [comment]
Seconding this camera issue, the rest works. Would be cool to see it addressed.

**Comment by melancholie** [comment]
Specifically what appears to be happening is that the left trigger axis swapped with one of the right stick axes. This is what leads to the flying upward of the camera. It's likely a direct result of the DualSense having slightly different axis labels than whatever controller it is being recognised as. Likely not a giant fix necessary.

**Comment by 1eer0y** [comment]
30.04.2024 steam deck, flying camera(

**Comment by roobeekspamma** [comment]
any updates on this?

**Comment by w-i-s-n** [comment]
been viewing this thread for a while now. finally installed linux, doesn't work in windows (camera goes up). works perfectly well on arch

**Comment by t4bby** [comment]
Latest Dota2 patch `7.36`, fixes the issue for Flying Camera for controllers at least on Steam Deck device.

**Comment by Karandash99** [comment]
doesn't work for me with my dualsense.

**Comment by w-i-s-n** [comment]
> been viewing this thread for a while now. finally installed linux, doesn't work in windows (camera goes up). works perfectly well on arch btw

after doing an actual game with a controller. I do not recommend it. It's still broken, not sure for Steam OS but for me it crashes the entire system after 10 minutes. Logs me out entirely of the pc

**Comment by BrainRTP** [comment]
Not work on steam deck today. 
I try all things, args, settings and etc. 

Do you now how to enable it today?

**Comment by mirddes** [comment]
https://github.com/ValveSoftware/Dota2-Gameplay/issues/27564

**Comment by ice-blaze** [comment]
I close the issue since it has been fixed on linux and windows.

**Comment by mirddes** [comment]
it not fixed, it's still missing on windows. ive got a controller plugged in and dota does nothing. 3 years ago i had to unplug my controller when i bumped it because of how seamlessly integrated controller support was back then IT JUST WORKED WITH ZERO CONFIGURATION and now it's clearly missing.

reopen this

**Comment by mirddes** [comment]
ok it functions but it crashes the game lots. and i can't seem to work out how to deny.

**Comment by ice-blaze** [comment]
@mirddes I haven't done a full game but on Windows it seems to work correctly. Also denying seems fine. The only thing I never could do with the gamepad is to activate those "neutral" map wards.
