### ISSUE TITLE
i cant matchmake in dota2

### ISSUE THREAD

**Issue by aurellllllllll** [ValveSoftware/Dota2-Gameplay#16042]
### Description

i cant seem to matchmake in dota2, when i try to matchmake it says that my valve anti-cheat(VAC) was unable to verify that my machine is secure. failure to fix this may result the inability to play online.

### Screenshots

![image](https://github.com/ValveSoftware/Dota2-Gameplay/assets/164642440/f8a85997-4703-4089-99f2-b3f8e4378bf7)

**Comment by commentator24** [comment]
#15978 your pc has memory issues?
someone said  it's fixed by moving game to another disk. Then can move it back to original.

**Comment by Kr1st0fh** [comment]
> #15978 your pc has memory issues? someone said it's fixed by moving game to another disk. Then can move it back to original.

Hello. I'm the another disk guy. Well bug is back. So I think I have to move to another diks once again. Horrible bug.

**Comment by bonkmaykrQ** [comment]
Had this issue across multiple installs. Tried removing DLC, already reinstalled once, already verified checksums. I'm on Linux if that matters. Both Native & Proton do not work. VAC works fine for Counter-strike 2 and everything else, DotA is the only game that won't let me connect to matchmaking. Clicking More Info doesn't open my browser.
