### ISSUE TITLE
Teammates tab under history shows nothing in the Dota client

### ISSUE THREAD

**Issue by minbastu** [ValveSoftware/Dota2-Gameplay#21618]
When you go to the teammates tab in the Dota client to see your stats with teammates (from match history) it shows nothing. I have asked my friends and they also see nothing. Please fix oh you great valve! Have a good day and thank you.

**Comment by Hako-Ben** [comment]
Same here!
![image](https://github.com/user-attachments/assets/86b8ae7a-44ac-41d3-89f2-3ab912362221)

**Comment by schizocatto** [comment]
same

**Comment by schizocatto** [comment]
I believe this stems from the issue below, where opening the Teammates tab crashes the game. I think fixing that came with the cost of reprogramming the entire query part for that tab so we might not be able to see anything for a while.

https://github.com/ValveSoftware/Dota2-Gameplay/issues/21428

**Comment by robert-gogolan** [comment]
Happens to me also, teammates tab is empty.

**Comment by kostakis** [comment]
Please fix @eugene-valve

**Comment by dazzle-me** [comment]
shallow ping :] I'm waiting for this feature to be back, I want to see with whom I played most of my games again! 
we have such a history

**Comment by SlavikTraktor** [comment]
Me and my friends also have this issue, valve please help

**Comment by KyuVan** [comment]
@schizocatto 6 months without fixing this issue. Can this issue be prioritized anytime soon?

**Comment by kostakis** [comment]
For the love of god can we fix this already

**Comment by jericoluislua** [comment]
Is there any status update on this?

**Comment by kostakis** [comment]
Wow still not a fix

**Comment by kostakis** [comment]
It is fixed after the new update

**Comment by Hako-Ben** [comment]
Not yet fixed! Last game shown is 5/21/2025. All games played after this date are not reflected.
