### ISSUE TITLE
7.32 Brewmaster - Primal Companion not getting the bonus HP from talent

### ISSUE THREAD

**Issue by vagabondmaru** [ValveSoftware/Dota2-Gameplay#2313]
### Ability name

Brewnaster - Primal Companion

### Description

tried this in demo mode:

1. load Brewmaster
2. level up to max
3. summon Primal Companion and note the HP (for Wind: 2000)
4. get the +1200 Brewlings Health talent
5. check Brewling HP (still the same from #3, e.g. for WInd still at 2000hp)
6. try resummoning a new Primal Companion
7. check the HP (still at 2000hp)

One more thing (not exactly a bug perhaps):
- is it intended that Primal Companion requires the ult (Primal Split) and Drunken Brawler leveled up? (i suppose it is, and is very unlikely that a serious player would intentionally skip these before getting aghs anyway)
(i noticed this because i first loaded the demo mode then took aghs before leveling up the hero and no brewling came out on cast of Primal Companion)

Anyway thanks for reading and hopefully looking in it

### Example Match ID (and possibly Timestamp)

tried in demo mode

**Comment by shaileshgarg** [comment]
This has been fixed

**Comment by vagabondmaru** [comment]
just checked again today in demo mode, problem still persists
