### ISSUE TITLE
 bug with shift pack

### ISSUE THREAD

**Issue by vanoavdonin** [ValveSoftware/Dota2-Gameplay#23385]
### Ability name

phase shift 

### Description

when you use shift and cancel action very quickly, the hero is not in shift, and at the same time you cannot control him, there is also a bug that I am sure you know about with switching the second spell pack, the hero comes out of shift

![photo_2024-12-22_13-42-50](https://github.com/user-attachments/assets/3e1a5e27-0443-4814-aba5-f61e72e76831)

### Example Match ID (and possibly Timestamp)

in any game

**Comment by Avarise831** [comment]
#19760

**Comment by maakep** [comment]
Fixed

**Comment by Bu3nyy** [comment]
Not fully fixed

Phase Shift and Tricks of the Trade are still interrupted by items with the DOTA_ABILITY_BEHAVIOR_DONT_CANCEL_CHANNEL flag.


This flag specifically allows abilities to be cast while channeling (usually used by items, such as Phase Boots and Shiva's Guard), but they partially still interrupt Phase Shift and Tricks of the Trade. They stop the ability effects, but the channeling itself continues, meaning you're channeling nothing.
