### ISSUE TITLE
Teleport Requires Hold/Stop

### ISSUE THREAD

**Issue by OldAkki** [ValveSoftware/Dota2-Gameplay#24193]
### Ability name

Shadow Walk

### Description

It seems that this feature is currently not working as it is before. Before with this on, you can use shadow walk or shadow realm after casting a tp prompting you to tp in invisible or shadow realm state. Now if this is on, the feature will not allow you to go on Invisible mode or in shadow realm mode while using a teleport/ twin gate or capturing outpost. But if this is currently off it will allow you to Teleport on shadow walk mode or shadow realm mode but prompting to move will cancel the tp

### Example Match ID (and possibly Timestamp)

8181169381 35:01 - 35:05

**Comment by seowth** [comment]
Yup this bug came back once again with the new patch. It's been fixed and rebugged intermittently quite a few times. 

https://github.com/ValveSoftware/Dota2-Gameplay/issues/23297

Please fix

**Comment by SahilValve** [comment]
Thanks for the report - am looking into it.

**Comment by SahilValve** [comment]
I have fixed the problem with Shadow Walk but Shadow Realm looks to be working correctly. Can you provide a video of Shadow Realm not working?

**Comment by OldAkki** [comment]
I forgot to remove the shadow realm part but it seems the shadow walk bug is still in game. It Seem's that you are not able to cast any invisibility (glimmer, shadow walk, shadow blade) while casting a tp not how it works before but turning off teleport requires hold or stop will have it work but that's just not how it works before.

**Comment by SahilValve** [comment]
The shadow walk issue will be fixed in a future patch. I cannot seem to reproduce the invisibility problem you are describing - I am able to cast glimmer cape on myself while tping. Can you post a video of it not working for you?

**Comment by seowth** [comment]
I just tested shadow walk and glimmer cape while tp-ing, and they both seem to work.

Thank you for the fix SahilValve, hopefully it persists through future patches xD

**Comment by OldAkki** [comment]
I think its fix

**Comment by SahilValve** [comment]
Thanks for confirming!
