### ISSUE TITLE
Hoodwink Ult Crashes Games

### ISSUE THREAD

**Issue by redsky17** [ValveSoftware/Dota2-Gameplay#24334]
### Ability name

Sharpshooter

### Description

Game crashes as soon as hoodwink ult is activated.  Ends up with game not being scored.

### Example Match ID (and possibly Timestamp)

000000000000000

**Comment by redsky17** [comment]
I would add a match ID, however, unscored matches don't show up in my history so I don't know what they are.

**Comment by ggaldino** [comment]
same problem here

**Comment by redsky17** [comment]
Looks like it's fixed as of the patch that just happened.

**Comment by megapetazeta** [comment]
> Looks like it's fixed as of the patch that just happened.

Still crashes for me.

**Comment by Drewoob** [comment]
tried 2 matches in a row, hoodwink does in fact still crash the game when sharpshooter is used, or moreso attempted

**Comment by redsky17** [comment]
I was wrong.  I tried it in the 'demo hero' mode and it worked but it just crashed in a game I was in.

**Comment by redsky17** [comment]
Unfortunately I cannot reopen this issue.

**Comment by Drewoob** [comment]
and so now issues are opened that still address this issue, but are linked this closed issue and tagged as "duplicate" when the issue is not fixed..welp

**Comment by yoshilovescookies** [comment]
> and so now issues are opened that still address this issue, but are linked this closed issue and tagged as "duplicate" when the issue is not fixed..welp

should be okay, they'll see other new posts that should have new timestamps that show the issue isn't fixed with the new patch.

**Comment by Drewoob** [comment]
they launched another patch i think, maybe this one will be the one

**Comment by megapetazeta** [comment]
> they launched another patch i think, maybe this one will be the one

It seems they've fixed it. At least testing the hero offline no longer crashes the game. Thank you Valve.

![Image](https://github.com/user-attachments/assets/e71fc61d-49d5-45d0-be0c-b782979e41f1)

**Comment by yoshilovescookies** [comment]
@megapetazeta can you try in an online match?

**Comment by yoshilovescookies** [comment]
https://github.com/user-attachments/assets/c04758bc-1fe4-439c-8aec-fd231a409656

video of crash

**Comment by megapetazeta** [comment]
No Issues Now on Custom Match on Online Server, last patch

![Image](https://github.com/user-attachments/assets/a3b376c3-079a-4bba-90ff-14a0276e2c3b)

**Comment by yoshilovescookies** [comment]
amazing!  thank you for giving it a go!

**Comment by Drewoob** [comment]
after a 72 minute match, i can confirm that, in the end, the bug seems to have been patched
