### ISSUE TITLE
[Shadow Shaman] "Eyes in the Endless Dark-Head"+"Mysterious Vagabond's Pack". Stretched textures.

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#24846]
### Cosmetic Item Name

"Eyes in the Endless Dark-Head"+"Mysterious Vagabond's Pack"

### Description

The combination of these two items causes a texture stretching bug.
![Image](https://github.com/user-attachments/assets/0ffa0c9b-5d5c-4ae5-bbdd-85be5e20c09a)

### Example Match ID

-

**Comment by ezhhh** [comment]
that hero needs to be deleted from dota lol annoying shit

**Comment by Polykomodo** [comment]
Fixed

**Comment by Astiberon** [comment]
> Fixed

everything is still broken for now((
<img width="736" height="525" alt="Image" src="https://github.com/user-attachments/assets/35938bbf-bc07-450f-9e46-f698d2c6e70a" />
