### ISSUE TITLE
Gris-Gris and Black Grimoire Bug

### ISSUE THREAD

**Issue by Redict** [ValveSoftware/Dota2-Gameplay#25479]
Bug with Gris-Gris and Black Grimoire transferring has been fixed: it is no longer possible to put them up for sale, so it is no longer possible to transfer them to another hero. However, Gris-Gris or Black Grimoire will not be removed from the inventory when used from the courier (click on the item → Select the courier (F2 by default) → Click “Consume Item”). 
There are 2 ways to abuse this bug:
1. Witch Doctor can use Gris-Gris through the courier being dead, which will help to buyback when running low on gold.
2. Warlock can use Black Grimoire twice:
 - The first time through the courier, because of which Black Grimoire will not be lost.
 - Next, fill the main inventory slots with items and choose a neutral item.
 - Since Black Grimoire did not disappear after the first use, it will give experience once more, after which it will disappear and the item of your choice will appear in its place.

https://github.com/user-attachments/assets/16a4ff19-baff-498e-b137-2a390972b714

**Comment by chrisf-valve** [comment]
There was a client update released an hour ago that should resolve this issue.

Thanks for the report!

**Comment by Avarise831** [comment]
> There was a client update released an hour ago that should resolve this issue.
> 
> Thanks for the report!

Warlock Black Grimoire
7.38b XP per kill /assist decresed from 250 to 200
you forgot to make these changes fix please :)
