### ISSUE TITLE
Dota 2 7.39 Drops After Going To Settings

### ISSUE THREAD

**Issue by dorogovtsev** [ValveSoftware/Dota2-Gameplay#25824]
Greetings!
I have a problem with quiting Dota 2 after updating it to 7.39 and going to Setting in Main Window of the game.
Please help to fix it.
My profile name is marko_ua12
Many many thanks!

**Comment by dorogovtsev** [comment]
Even I can use my microphone in game...

**Comment by thearminz** [comment]
yes me too , when i go to setting or use my mic

**Comment by dorogovtsev** [comment]
If someone knows what we could do, please write here.
My PC specs:
HexaCore AMD Phenom II X6 1055T, 3220 MHz (14 x 230)
DDR3-1600 (800 МГц) 8GB x 2
Северный мост: AMD RX780
Северный мост: AMD K10 IMC
Южный мост: AMD SB710
NVIDIA GeForce GT 730 2Gb Дата драйвера	13.09.2021
Операционная система	Microsoft Windows 10 Home

**Comment by drama64** [comment]
Solution: Everything was resolved by simply disabling app access to the microphone in Windows settings, so it’s directly linked to the excessive CPU load caused by the microphone being connected when opening the settings.

**Comment by dorogovtsev** [comment]
Is there any solution to use my microphone in the game?
Don't you know will it fixed?

**Comment by drama64** [comment]
No, it's currently not possible with any console commands or startup parameters, so that's most likely the only solution until the update

**Comment by drama64** [comment]
even if you turn off the microphone, go to the settings, set everything you need, then turn on the microphone, then when you click on the button to turn on the microphone in the game, it also crashes.

**Comment by SahilValve** [comment]
Hello, are you all experiencing these issues still?

**Comment by dorogovtsev** [comment]
Greetings.
Yes, just tested, still drops after enabling mic in windows...
Do you have any solutions?

**Comment by drama64** [comment]
> Hello, are you all experiencing these issues still?

Hi, I'm attaching a support request with more information about the problem. 

---

User | May 23, 19:17 | 8 days ago
 After updating to version 7.39, the game freezes and crashes within 1 second of opening settings.  

User | May 23, 20:19 | 8 days ago
 Issue appears Steam-related. After exiting Steam and launching the game directly from its folder, the menu worked normally.  

User | May 24, 10:56 | 7 days ago  
 Solution found: Disabling app microphone access in Windows settings resolved the crash. Caused by excessive CPU load when microphone is active during settings access.  

User | May 24, 13:26 | 7 days ago  
 Even if you turn off the microphone, go to the settings, set everything you need, then turn on the microphone, then when you click on the button to turn on the microphone in the game, it also crashes. 

User | May 24, 13:28 | 7 days ago  
Conclusion: Microphone-related issue, not settings panel.  

User | May 24, 13:29 | 7 days ago  
Note: Crash occurs even with "simplified microphone activation" enabled.  

User | May 24, 13:33 | 7 days ago  
GitHub issue report:  
https://github.com/ValveSoftware/Dota2-Gameplay/issues/25805#issuecomment-2906628958  

---

Support (Bonnie) | May 24, 22:19 | 7 days ago
 Hello!  
   
 We cannot manually adjust restrictions, match outcomes, or rankings.  
   
 To troubleshoot:  
 1. Generate a full system report  
 2. Attach it for investigation.  

---

User | May 25, 08:43 | 7 days ago  
 Attached: msinfo32.nfo 
Unfortunately, GitHub does not support .nfo files

---

Support (Miguel) | May 26, 15:44 | 5 days ago
   
 Required actions:  
 1. Test on another machine/different account  
 2. Attach recent crash dumps (max 2) from:  
    - C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta 
    - C:\Program Files (x86)\Steam\dumps
 3. Follow [Basic Troubleshooting](https://help.steampowered.com)  

---

User | May 26, 17:52 | 5 days ago 
Yes, from what I’ve tried:
- Fully reinstalled the game, deleting all local configs.
- Disabled Steam Cloud sync.
- Attempted to access settings from two different accounts.
- Changed launch parameters.
- Disabled voice chat via console commands.
- Enabled simplified microphone activation settings.

The only things that worked were restricting the application’s access to the microphone and launching dota2.exe directly from the root folder with Steam closed.

While researching whether others faced this issue, I found around 20 threads across various forums (including Reddit) and GitHub issues describing the same problem. After I shared the solution, people confirmed it worked for everyone affected. Those who reported the issue mentioned having low-spec computers, and one user noted that clicking the microphone button in the voice chat (without even entering settings) also crashes the game.

I’ll now reproduce the issue a few times and attach the most recent dump files to ensure the information is up-to-date.

The first two files from C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\bin\win64
and the next two files from C:\Program Files (x86)\Steam\dumps 
Unfortunately, GitHub does not support .mdmp and .dmp files

---

I've attached all these files in archives so you can see the information.

[msinfo32.zip](https://github.com/user-attachments/files/20538275/msinfo32.zip)

[dota_dumps.zip](https://github.com/user-attachments/files/20538277/dota_dumps.zip)

**Comment by drama64** [comment]
> Hello, are you all experiencing these issues still?

I apologize for the confusion, I couldn't check but now I can say the problem is solved. thanks for the work!

**Comment by dorogovtsev** [comment]
The problem is not solved, because before the update 7.39 it all work...

**Comment by drama64** [comment]
> The problem is not solved, because before the update 7.39 it all work...

I created a new account and it worked on it, but I haven't checked the previous accounts for the last 3 days

**Comment by dorogovtsev** [comment]
Do you think there is a difference between old and new accounts? I have 3 Steam accounts and dota crashes at all after enabling microphone. I wanna say that everything was good before dota update 7.39

**Comment by drama64** [comment]
I had exactly the same problem, it didn't work on two accounts, but I created a new account and everything worked, you can try it out

**Comment by dorogovtsev** [comment]
After latest micro update problem with activating microphone is solved. Just checked 🙂
