### ISSUE TITLE
Axe Immortal Visual Bug

### ISSUE THREAD

**Issue by FangedLion** [ValveSoftware/Dota2-Gameplay#26097]
### Cosmetic Item Name

Crucible of Rile, Golden Crucible of Rile

### Description

The ambient effects over the eyes are misaligned. Currently, they go inwards when previously (as intended) they should be pointing outwards.

### Example Match ID

8311018762

### Screenshots

![Image](https://github.com/user-attachments/assets/84ef4157-095a-4168-ab34-e46ccdb01937)

![Image](https://github.com/user-attachments/assets/fb70d271-827c-400c-824a-83d21c5eb4b3)

**Comment by Astiberon** [comment]
![Image](https://github.com/user-attachments/assets/301bdc66-83e9-4324-841c-99fa92438c1d)

**Comment by jeffhill** [comment]
This is fixed in the build we just shipped. Thank you for the bug report!

**Comment by FangedLion** [comment]
Hi, this bug still remains the same in the most recent steam update. Could the issue please be reopened?

![Image](https://github.com/user-attachments/assets/d2b97698-9adf-4351-bbb3-82e23caccf94)

**Comment by Astiberon** [comment]
> This is fixed in the build we just shipped. Thank you for the bug report!

Hello Jeff, This bug is still not fixed.

![Image](https://github.com/user-attachments/assets/df0420e5-5e64-4df0-ae79-38d5a60d8313)

**Comment by bizzozeron** [comment]
Fixed in future update.  Also fixed the gold one.

**Comment by Astiberon** [comment]
![Image](https://github.com/user-attachments/assets/9033e768-7da4-4c89-93dc-91d8dcee1ffc)
