### ISSUE TITLE
Courier does not bring you items if you lock them for combining

### ISSUE THREAD

**Issue by neimovirne** [ValveSoftware/Dota2-Gameplay#26161]
### Description

The courier takes the items but never brings it to you and flies back with the locked item to a fountain.

### Example Match ID (and possibly Timestamp)

8313455396, time 10:24-10:48

### Screenshots

https://github.com/user-attachments/assets/69f1e006-20b9-4893-9d74-faaf0e3dde9c

**Comment by SahilValve** [comment]
We've fixed this for the next update. Thanks for the report.

**Comment by neimovirne** [comment]
> We've fixed this for the next update. Thanks for the report.

When will the update go live? cause I just tested it 2 minutes ago and the bug still exists

EDITED: just got the update, bug is fixed
