### ISSUE TITLE
! COURIER BUG PLS FIX ASAP !(Deliver Items Hotkey BUG)

### ISSUE THREAD

**Issue by justinbgumolom484** [ValveSoftware/Dota2-Gameplay#26433]
### Description

GAME RUINING BUG --> 
COURIER RANDOMLY GETS STUCK when pressing the hotkey *DELIVER ITEMS* --> but delivers only when you manually use the hotkey *TRANSFER ITEMS*   

-->this issue occured after the patch 7.39.

--> You have to manually  select the courier --> use the @Transfer Items for the items to deliver to you.

If you use the direct @Deliver Items hotkey , at times the courier randomly freezes and won't send the items to you, even though the courier is giving a "SIGNAL" that "it's ON THE WAY ICON" 

### Screenshots

![Image](https://github.com/user-attachments/assets/5f88c66f-3d4c-4a9c-bc31-9ebff779ad3c)

, **(this is highly important as you can't always check if your courier is coming since you're reading the map and fights)**

![Image](https://github.com/user-attachments/assets/fd0d3314-4a51-4c7b-b4f9-3f11b3944940)

check the circle icon on the bottom right  --> show's that its' delivering but it's stuck 
I *clicked* Alt+3 @DeliverItem + Speedburst command to Deliver the item on 23:03
(check the time 23:04 -->23:09, courier is literally stuck, it only sent me the items when I manually command the courier to transfer items, this happens randomly; at times it sends or ;;it doesn't, 

![Image](https://github.com/user-attachments/assets/f9f44afe-1a8c-42db-8f6e-ed52fe530744)

tldr;
-courier doesn't send items when you command it to deliver,, -->it gets stuck while giving you the information that it's delivering, yet it remains stuck.

more info; 
-bug occurs both in secret shop and in base,
-bug occurs 50 / 50 during the game (RANDOMLY AT ANYTIME), it sends, and sometimes it's stuck like this.
- I'm running dota2 in LINUX, CachyOS, (steam-native)

**Comment by justinbgumolom484** [comment]
HELP

**Comment by justinbgumolom484** [comment]
**GAME ID : 8327442066**
devs, I can't upload the .dem file of the replay
the game ID isn't public since this is a 8.5k+ ranked game, but I assume you guys can see this still

**Comment by justinbgumolom484** [comment]
HELP

**Comment by zzxcqzard** [comment]
да разрабу похуй, чильни ))

**Comment by Nathanael-Valve** [comment]
Should be fixed now.

**Comment by justinbgumolom484** [comment]
@Nathanael-Valve  unfurtunately, just now, the bug came back. I'm requesting to re-asses this bug please, with due respect @Valve, Thank you!

**Comment by justinbgumolom484** [comment]
The bug cameback just now, courier randomly does not send after commanding it to send.

**Comment by justinbgumolom484** [comment]
same issue with, https://github.com/ValveSoftware/Dota2-Gameplay/issues/26399

**Comment by Nathanael-Valve** [comment]
Discussion moved to https://github.com/ValveSoftware/Dota2-Gameplay/issues/26631
