### ISSUE TITLE
Dota2 crashes on MacOS Tahoe version 26 beta

### ISSUE THREAD

**Issue by mylaluna** [ValveSoftware/Dota2-Gameplay#26450]
### Description

After I upgrade to MacOS Tahoe which is just released today, I find Dota 2 crashes with the same graphic setting I had in previous MacOS version.

Enviornment:
- Macbook M1 Max
- MacOS Tahoe version 26
- 4k144hz gaming monitor

Dota 2 Graphic setting:
- 16:9, 4k 95hz, Exclusive Fullscreen
- Desktop-friendly fullscreen minimizes on focus loss: off
- Use advanced setting
  - Anti-Aliasing
  - VSync
  - Compute Shaders
  - Texture Quality: High
  - Effects: Low
  - Shadow Quality: off
  - Game Screen Render Quality: 75%
  - FidelityFX Super Resolution: on
  - Maximum frames per second allowed: 90
  - Dashboard maximum frames per second: 60

Crashes:
- on scrolling the setting menu (fast scrolling down)
- on changing "Desktop-friendly fullscreen minimizes on focus loss" setting
- on loading the hero 3D model
- on entering hero demo

I then changed my graphic settings to the lowest resolution, quality and run in window mode but the crashes remained.

It seems that Dota2 can crash in the new MacOS Tahoe at many different and unpredictable occasions. The entire game becomes very unstable. This may indicate the game has general compatibility issues with the new MacOS management of graphic resource. 

Additionally, I find when Dota2 is shutdown, either due to crash or normal close, Steam still thinks the game is running and prevent you from reopening the game again. The only solution is to turn Steam off entirely.
This behaviour also results in the system app crash report window cannot be correctly launched. 

In summary, Dota2 is pretty much unplayable in the MacOS Tahoe at the moment. 

**For any Mac Dota2 player, please don't upgrade to the MacOS Tahoe until this issue is solved.** 

Downgrading MacOS to the previous version requires complex process.

**Comment by uvkudulla** [comment]
Same, I also faced the same issue after upgrading to MacOS Tahoe, reinstallation of Dota also doesn't work.

**Comment by mehmet-erdogdu** [comment]
place fix this

**Comment by atone77721** [comment]
same issue with my M3 Max

**Comment by farnabaz** [comment]
For me, it opens the game but does not connect to the coordinator, and when I tried to demo a hero, I received this error

> Failed to initialize Steamworks SDK for gameserver.  Could not determine Steam client install directory.
<img width="372" alt="Image" src="https://github.com/user-attachments/assets/df0e5d12-38ad-4506-892f-70b7cec1c1ee" />

**Comment by GoodGuyDany** [comment]
Same thing, dota seems to be running fine until it just quits. Steam still thinks it's running, though.

**Comment by Shawn0779** [comment]
Every time I launch the game I am getting "lost connection to steam" error message so I cannot play online matches. Tried to play with bots no problem so far in terms of unexpected crashes.

**Comment by showme032** [comment]
Damn, saw this post 1 hour later than I should have 🥲

**Comment by axiom24** [comment]
Hey can you try stream in invisible mode and then try the game.

**Comment by atone77721** [comment]
Update to Steam Arm beta it will fix the issue.

**Comment by mylaluna** [comment]
> Update to Steam Arm beta it will fix the issue.

Thank you for the suggestion. 
I have just upgraded my Steam to beta version. 
It looks like the Dota 2 is running more stable but with some performance drop.
I think I need to play a couple of games to further test its stability.

You are welcome to join this test together:
Steam > Preferences > Interface > Client Beta Participation - Steam Beta Update

So it is the Steam client rather than Dota 2 that has compatibility issues after all.
I am glad there is a Report a bug button in the menu path above.

I also noticed the Steam Arm beta is just released yesterday June 12th. 
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/545611272206420782

Reddit discussion:
https://www.reddit.com/r/macgaming/comments/1l9vnnc/steam_will_finally_release_an_apple/

What a timing!

-----------------------------
Tests with Steam Arm beta:
1. noticeable game stuttering and performance drop
2. crashed after a turbo game

**Comment by showme032** [comment]
Yes, updating to arm version of steam makes dota not crash anymore, but it's borderline unplayable with performance drop. Would still suggest staying away from macos 26 if you wish to play dota.

**Comment by caderedark** [comment]
Has anyone found a way to solve the lags?I installed the second developer beta, so far everything is the same.

**Comment by caderedark** [comment]
Has anyone found a way to solve the lags?I installed the second developer beta, so far everything is the same.

**Comment by Shawn0779** [comment]
Does anybody know when Steam ARM will get official release? Currently running beta version

**Comment by mylaluna** [comment]
Yesterday, I upgraded my MacOS Tahoe 26 to beta 2 and I experienced even worse performance drop.
My dota 2 game fps was down to 45-50 average. 

I downloaded Macs Fan Control app and set my laptop fans speed to above 3200 RPM.
The average fps is improved to 55-60, which is still not ideal. 
As higher fan speed creates noticeable noise so this may be my solution temporarily.

**Comment by oglenyaboss** [comment]
there is some memory drain bug in dota 40+ gb ram usage after one ranked game only quit and open again every 20 minutes can solve fps drops

**Comment by mylaluna** [comment]
> there is some memory drain bug in dota 40+ gb ram usage after one ranked game only quit and open again every 20 minutes can solve fps drops

I just verified this behaviour. I will open a new issue for this.
I am not very sure if normal version MacOS has this issue or not.

**Comment by mylaluna** [comment]
Verify Dota2 doesn't crash anymore with Steam Arm beta.
The memory leak and performance drop may just be fixed in the latest MacOS 26 beta.

**Comment by nimseven7** [comment]
Didn't see this thread until now after upgrading to MacOS 26 yesterday 🥲 
Dota 2 still crashes, even with beta steam client (the arm one).
Trying to play on M4 pro 24GB.

**Comment by abduraufsherkulov** [comment]
@nimseven7 Did you figure it out? I am also having the same problem

**Comment by nimseven7** [comment]
> [@nimseven7](https://github.com/nimseven7) Did you figure it out? I am also having the same problem

@abduraufsherkulov Nope. I just opened an issue here: https://github.com/ValveSoftware/Dota-2/issues/3328
