### ISSUE TITLE
CPU clocking down

### ISSUE THREAD

**Issue by dipimon** [ValveSoftware/Dota2-Gameplay#27023]
### Description

Since 2 days (23. Jul 2025) I have a strange bug with Dota. When launching the game my CPU clocks down to 800MHz.
I assumed it is a hardware problem but could not find anything wrong in this direction. The CPU temperature is at 30°C - 40°C while the PL1/PL2 is set to 4096W. Windows Powersettings are on ulta... 
I have tested a lot of different games and this issue only occurs in Dota.

I did not find anything like this bug.

CPU - I7-13700k

### Screenshots

<img width="358" height="578" alt="Image" src="https://github.com/user-attachments/assets/1f34d67b-fa06-48d2-b723-046fb90c2c46" />

**Comment by Fivedota** [comment]
Try restart without ever going into settings in Dota. I found out that if I enter settings I nedd to reboot dota completely because my CPU (7800 x3d) think it’s sleeptime after I enter setting at any point

**Comment by McAceNL** [comment]
I’m also experiencing this exact issue as of July 24th, 2025.

Specs:
- CPU: Intel Core i7-13700K
- GPU: NVIDIA RTX 4080
- RAM: 32GB
- OS: Windows 11
- Monitor: 3440x1440 @ 144Hz

The game starts at 144 FPS but drops to 3–4 FPS shortly after launch or when entering a match. The main menu and in-game assets load extremely slowly. The game is basically unplayable in this state.

What seems particularly unusual is that **my CPU clock speed drops to 0.80 GHz while Dota 2 is running**. As soon as I close the game, the CPU returns to normal clock speeds. This only happens with Dota 2 — no other games or applications trigger it.

What I’ve tried so far:
- Restarted PC
- Verified game files via Steam
- Fully uninstalled and reinstalled Dota 2

None of these steps resolved the issue. Happy to provide logs or further details if that helps.

**Comment by Fivedota** [comment]
I think it's fixed now right? Patched around 12 hours ago.

Edit: Or probably less than 12 hours

**Comment by dipimon** [comment]
No the problem persists.

What I found in HWInfo the for some reason the Core Power Limit and the Package/Ring Power Limit is exceeded.

<img width="580" height="202" alt="Image" src="https://github.com/user-attachments/assets/aa8047de-14de-4e50-b33b-ea8e034a3f68" />

**Comment by McAceNL** [comment]
Jup, same issue here. It's still happening. Same CPU too, so that might be an underlining factor

Edit: Just found out that by putting the PC into sleepmode and wake it up again restores the CPU GHz. It is not a sustainable sollution but a work-around.

**Comment by TheDeepT** [comment]
Same exact issue here, please help :)

**Comment by efmiglioranza** [comment]
Same here, the only quick fix I found for now is to launch the game, put the PC to sleep (with the game still open) and wake up. Also, tested with other games and only Dota is bugged.
Edit: same CPU too, 13700K

**Comment by gradygriff** [comment]
same issue

12th Gen Intel(R) Core(TM) i7-12700F
NVIDIA GeForce RTX 3080

**Comment by mariobiermeier** [comment]
same here

12th Gen Intel(R) Core(TM) i7-12700K
NVIDIA GeForce RTX 3080

**Comment by cinconumbercerog** [comment]
Hi.
Check if an external application is messing with your power settings. Uninstalling MSI Companion fixed it.

Figured it out by checking Event Viewer System logs and seeing that, after opening Dota 2, the power policy was changed by MSICenter.exe

**Comment by natemajor** [comment]
Uninstalled MSI Afterburner and immediately started working . CPU was also clocking down to 800mhz before on an i7-12700k. Pretty upset because I thought my CPU was overheating. My motherboard would beep and shut the system down. I bought a new cooler at a local store before I figured it out.

**Comment by efmiglioranza** [comment]
Seems like it, just uninstalled MSI Game Whatever (can't remember the name, not the companion, and it doesn't show up anymore in the MSI Center) and now it's working.

**Comment by TheDeepT** [comment]
Worked as well for me! thx guys

**Comment by dipimon** [comment]
Yes it also worked for me. Thank you guys. Now it's time to play doto
