### ISSUE TITLE
The problem with the visual with the "Feast of Abscession" mix set "Cursed Cryptbreaker"

### ISSUE THREAD

**Issue by exlyxd** [ValveSoftware/Dota2-Gameplay#7053]
### Cosmetic Item Name

Feast of Abscession

### Description

I have a problem with the effects of the item "Feast of Abscession" on the hero "Pudge", and I ask you as soon as possible to fix this bug, in the screenshot entitled "Before" shows how it was before the last update, all effects were normal, but in the screenshot entitled "After" shows the result after the last update, some effects are simply missing.

### Example Match ID

7027867916

### Screenshots

![After](https://user-images.githubusercontent.com/126154440/220885979-2dcfb5c4-0271-47d5-9dca-bbc76f91baa2.png)
![Before](https://user-images.githubusercontent.com/126154440/220885992-3abbdde0-244b-4234-b53e-e21db9755deb.png)

**Comment by shaileshgarg** [comment]
This was fixed.

**Comment by exlyxd** [comment]
> This was fixed.

this not fixed

**Comment by shaileshgarg** [comment]
![Screenshot 2023-04-07 210147](https://user-images.githubusercontent.com/26450759/230635774-fe9e1cae-ebc6-4421-aac4-bc644a33e15b.png)

Looks normal to me.

**Comment by shaileshgarg** [comment]
https://www.reddit.com/r/DotA2/comments/118qlvz/as_of_today_i_noticed_that_they_removed_the/, also remember seeing this some time back on reddit, where this fix was confirmed.

**Comment by exlyxd** [comment]
> https://www.reddit.com/r/DotA2/comments/118qlvz/as_of_today_i_noticed_that_they_removed_the/, also remember seeing this some time back on reddit, where this fix was confirmed.

It should look like this, not like in your screenshot, look carefully at my "Before" and "After" screenshots before you write that the bug is fixed
![Before](https://user-images.githubusercontent.com/126154440/230652303-b3aa1bfb-a265-4cc8-8239-15b2b520bc24.png)
![Screenshot_1](https://user-images.githubusercontent.com/126154440/230652304-b6d3eed6-2ffd-497b-9bc5-d3fd34cf4823.jpg)

**Comment by exlyxd** [comment]
> https://www.reddit.com/r/DotA2/comments/118qlvz/as_of_today_i_noticed_that_they_removed_the/, also remember seeing this some time back on reddit, where this fix was confirmed.

![Uploading Before.png…]()
it should look like this, not like in your screenshot, look carefully at my screenshots "Before" and "After" before you write that the bug is fixed, look closely at the effects of magma

**Comment by exlyxd** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/126154440/230652520-5c0bac00-4846-4fdd-b20a-dc6da1005421.jpg)

**Comment by shaileshgarg** [comment]
What? The red effect flowing into cache set from the Arcana was the bug which was fixed.

**Comment by kyyyyylehead** [comment]
![image](https://user-images.githubusercontent.com/112140973/231937125-7559f6f3-343f-407f-a067-7772e002e976.png)
arcana mask still not being applied to cryptbreaker set

**Comment by kyyyyylehead** [comment]
In [this discussion](https://steamcommunity.com/sharedfiles/filedetails/comments/2875094035) the set author confirms that REMOVING the arcana effect from the set was a bug. Nothing else would make sense anyways because the arcana effect has to be masked onto the new assets by hand (it wouldn't show up perfectly on the hat, etc. if it wasn't)
