### ISSUE TITLE
[BUG] [VISUAL] Cosmetic from particle effects result in duplicate ghosting hero.

### ISSUE THREAD

**Issue by UnpopularOpinion** [ValveSoftware/Dota2-Gameplay#7116]
Does not happen with all particle effects, only some. 
Does not always happen, only sometimes that it occurs.
Two instances that I managed to capture are [sf arcana and chaos knight immortal](https://imgur.com/a/f5qrlS7).

[The following are my graphical settings for context](https://imgur.com/a/sTnH0a8)

**Comment by shaileshgarg** [comment]
![20230228220836_1](https://user-images.githubusercontent.com/26450759/221919000-8c7ad5a4-3b1a-472b-98cc-02b4b3ee80ac.jpg)

Same issue on Exort of Kid Invoker, Primal Beast when he is loaded first in Preview.

The issue is fixed when AA is on.

**Comment by UnpopularOpinion** [comment]
> Same issue on Exort of Kid Invoker, Primal Beast when he is loaded first in Preview.
Interesting that only exort has the issue. Could it be linked to fire / the blurry air around heat particle effect?

> The issue is fixed when AA is on.
With my settings, turning on anti-aliasing did not solve the issue for me
