### ISSUE TITLE
[Huskar] Immortal Searing Dominator+Armor of the Ember Demons.The helmet model is not attached to the hero's head (does not follow his movements).

### ISSUE THREAD

**Issue by Astiberon** [ValveSoftware/Dota2-Gameplay#7903]
### Cosmetic Item Name

Searing Dominator+Armor of the Ember Demons

### Description

The helmet model is not attached to the hero's head (does not follow his movements).
The bug occurs in combination with some items.The screenshot shows in combination with "Armor of the Ember Demons".
![image](https://user-images.githubusercontent.com/107125193/230738353-4a89ad43-e97c-4c7c-81e8-c84fb58382fe.png)
![image](https://user-images.githubusercontent.com/107125193/230738373-3323c6e6-ab37-4175-b26a-56726f59fa19.png)

### Example Match ID

-

**Comment by Avarise831** [comment]
#6480

**Comment by Astiberon** [comment]
> This issue is stale because it has been open for 365 days with no activity.

UP

**Comment by Polykomodo** [comment]
Fixed (the only issue with this item left is that the eyes particles are misaligned)

**Comment by Astiberon** [comment]
> Fixed (the only issue with this item left is that the eyes particles are misaligned)

still broken(
<img width="1443" height="1098" alt="Image" src="https://github.com/user-attachments/assets/31b938d0-a62f-441a-9f72-9e4e17383514" />

**Comment by Polykomodo** [comment]
Sorry for giving so much misinformation, I swear I thougth it was fixed, because I couldn't reproduce neither this bug or pudges/ss just tested all of that myself and was sure, but now i'm retesting them all and somehow bugs are present :(

**Comment by Astiberon** [comment]
FIXED

<img width="1182" height="714" alt="Image" src="https://github.com/user-attachments/assets/dc2b29ca-f828-43b9-8660-06c63935dc2b" />
